check50:
  files: &check50_files
    - !exclude "*"
    - !require hello.py
  checks:
    file exists:
      - run: ls | grep hello.py
        stdout: hello.py
        exit: 0
    testing hello:
      - run: python3 hello.py
        stdout: Hello, world!
        exit: 0
