check50:
  checks:
    file exists:
      - run: ls | grep hello.py
        stdout: hello.py
        exit: 0
    testing hello:
      - run: python3 hello.py
        stdout: Hello, world!
        exit: 0
